[package]
name = "mux-grapheme-arena"
description = "Arena allocator for extended grapheme clusters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
unicode-segmentation = { workspace = true }

[lints]
workspace = true
