[package]
name = "mux-proto"
description = "TF01 wire protocol implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mux-types.workspace = true
thiserror.workspace = true
crc32fast.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
