[package]
name = "termforge-server"
version = "0.0.2"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mux-kernel = { workspace = true }
mux-api = { workspace = true }
mux-config = { workspace = true }
anyhow = { workspace = true }
