[package]
name = "mux-format"
description = "tmux format string #{} evaluator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mux-types.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
