[package]
name = "mux-grid"
description = "Chunked COW terminal grid with dirty tracking"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mux-types = { workspace = true }
mux-grapheme-arena = { workspace = true }
bitvec = { workspace = true }

[lints]
workspace = true
