[package]
name = "mux-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mux-config = { workspace = true }
mux-kernel = { workspace = true }
mux-pty = { workspace = true }
mux-render = { workspace = true }
mux-term = { workspace = true }
mux-proto = { workspace = true }
mux-effects = { workspace = true }
