[package]
name = "tmux-vm"
description = "Headless terminal multiplexer for CI pipelines"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "tmux-vm"
path = "src/main.rs"

[dependencies]
mux-api = { workspace = true }
mux-kernel = { workspace = true }
mux-types = { workspace = true }
mux-time = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
